project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  cache: true

website:
  title: "blog.danieljsmith.org"
  site-url: "https://blog.danieljsmith.org"
  navbar:
    left:
      - text: "‚Üê Main Site"
        href: https://danieljsmith.org
    right:
      - about.qmd
      - icon: github
        href: https://github.com/danieljamessmith

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    grid:
      body-width: 1250px

code-block-bg: true
code-block-border-left: "#f59e0b"
highlight-style: atom-one



